import { test, expect } from '@playwright/test';

/**
 * AI-Generated API Test Suite — POST /api/register (reqres.in)
 * Generated by AITestCaseGenerator | Targets a real validating API
 * Author: David Odidi — QA Automation Engineer | github.com/davidodidi
 */

const BASE_URL = 'https://reqres.in';
const ENDPOINT = '/api/register';

const VALID_PAYLOAD = {
  email: 'eve.holt@reqres.in',
  password: 'pistol',
};

test.describe('POST /api/register', () => {

  test.describe('Happy Path', () => {
    test('should register successfully with valid credentials', async ({ request }) => {
      const startTime = Date.now();
      const response = await request.post(`${BASE_URL}${ENDPOINT}`, {
        data: VALID_PAYLOAD,
      });
      const responseTime = Date.now() - startTime;

      expect(response.status()).toBe(200);
      expect(responseTime).toBeLessThan(2000);

      const body = await response.json();
      expect(body).toHaveProperty('id');
      expect(body).toHaveProperty('token');
      expect(typeof body.id).toBe('number');
      expect(typeof body.token).toBe('string');
      expect(body.token.length).toBeGreaterThan(0);
    });
  });

  test.describe('Missing Required Fields', () => {
    test('should return 400 when password is missing', async ({ request }) => {
      const response = await request.post(`${BASE_URL}${ENDPOINT}`, {
        data: { email: 'eve.holt@reqres.in' },
      });

      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body).toHaveProperty('error');
      expect(body.error).toBeTruthy();
    });

    test('should return 400 when email is missing', async ({ request }) => {
      const response = await request.post(`${BASE_URL}${ENDPOINT}`, {
        data: { password: 'pistol' },
      });

      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body).toHaveProperty('error');
    });

    test('should return 400 when request body is empty', async ({ request }) => {
      const response = await request.post(`${BASE_URL}${ENDPOINT}`, {
        data: {},
      });

      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body).toHaveProperty('error');
    });
  });

  test.describe('Invalid Data', () => {
    test('should return 400 for unrecognised email', async ({ request }) => {
      const response = await request.post(`${BASE_URL}${ENDPOINT}`, {
        data: { email: 'unknown@fake.com', password: 'pistol' },
      });

      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body).toHaveProperty('error');
    });

    test('should return 400 when email is empty string', async ({ request }) => {
      const response = await request.post(`${BASE_URL}${ENDPOINT}`, {
        data: { email: '', password: 'pistol' },
      });

      expect(response.status()).toBe(400);
      const body = await response.json();
      expect(body).toHaveProperty('error');
    });
  });

  test.describe('Schema Validation', () => {
    test('should return id and token on successful registration', async ({ request }) => {
      const response = await request.post(`${BASE_URL}${ENDPOINT}`, {
        data: VALID_PAYLOAD,
      });

      expect(response.status()).toBe(200);
      const body = await response.json();

      expect(Object.keys(body)).toEqual(expect.arrayContaining(['id', 'token']));
      expect(typeof body.id).toBe('number');
      expect(typeof body.token).toBe('string');
    });

    test('should not return a password field in response', async ({ request }) => {
      const response = await request.post(`${BASE_URL}${ENDPOINT}`, {
        data: VALID_PAYLOAD,
      });

      const body = await response.json();
      expect(body).not.toHaveProperty('password');
    });
  });

  test.describe('Response Time', () => {
    test('should respond within 2000ms for valid request', async ({ request }) => {
      const startTime = Date.now();
      await request.post(`${BASE_URL}${ENDPOINT}`, { data: VALID_PAYLOAD });
      expect(Date.now() - startTime).toBeLessThan(2000);
    });

    test('should respond within 2000ms for invalid request', async ({ request }) => {
      const startTime = Date.now();
      await request.post(`${BASE_URL}${ENDPOINT}`, { data: {} });
      expect(Date.now() - startTime).toBeLessThan(2000);
    });
  });

});
